version: '3'
volumes:
  data:
networks:
  postgres-network:
services:
  db:
    container_name: guilbt_cadastropessoas_db
    image: postgres:9.6
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cadastropessoas42
    networks:
      - postgres-network
  service:
    container_name: guilbt_cadastropessoas
    image: maven:3.6-jdk-8
    ports:
      - 8081:8081
    networks:
      - postgres-network
    depends_on:
      - db
    volumes:
      - ./back:/cadastropessoas
    command: 
      bash -c "cd /cadastropessoas; mvn clean install; 
      java -jar target/cadastropessoas.jar"
  front:
    container_name: guilbt_cadastropessoas_front
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    volumes:
      - /front/node_modules
      - ./front:/front
    ports:
      - 3000:3000
    stdin_open: true    
    depends_on:
      - service